apiVersion: batch/v1
kind: Job
metadata:
  name: pgbench
spec:
  template:
    metadata:
      name: pgbench
    spec:
      containers:
      - name: pgbench
        image: thirtyx/postgres-benchmark:0.0.2-dev
        env:
          - name: PGPASSWORD
            value: password
          - name: PGUSER
            value: postgres
          - name: PGPORT
            value: "5432"
          - name: PGHOST
            value: postgres-todd-write
      restartPolicy: Never
