apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: edgexpostgres
spec:
  serviceName: "edgexpostgres"
  replicas: 3
  template:
    metadata:
      labels:
        app: edgexpostgres
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: postgres
        image: postgres
        env:
          - name: DB_PASS
            value: password
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        ports:
          - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: pg-data
  volumeClaimTemplates:
  - metadata:
      name: pg-data
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
