apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: CLUSER_NAME_TO_REPLACE-master
spec:
  # Always 1 replica, we have a different RC per
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        role: master
        cluster: CLUSER_NAME_TO_REPLACE
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: postgres
        image: thirtyx/postgres:0.0.1
        env:
          - name: POSTGRES_PASSWORD
            value: password
          - name: PGDATA
            value: /var/lib/postgresql/data
          - name: PGMOUNT
            value: /var/lib/postgresql
          - name: MEMBER_ROLE
            value: master
          - name: SYNCHONROUS_REPLICAS
            value: "SLAVE_NAMES"
        ports:
          - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name:  pg-data-CLUSER_NAME_TO_REPLACE-master
        #imagePullPolicy: Always
      volumes:
      - name: pg-data-CLUSER_NAME_TO_REPLACE-master
        persistentVolumeClaim:
          claimName: pg-data-CLUSER_NAME_TO_REPLACE-master

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pg-data-CLUSER_NAME_TO_REPLACE-master
  annotations:
    volume.beta.kubernetes.io/storage-class: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  # selector:
  #   matchLabels:
  #       app: postgres
  #       role: master
  #       cluster: CLUSER_NAME_TO_REPLACE
  #       MOUNT_ID: MOUNT_ID
