#This is the pet set for the master node
# Note that CLUSER_NAME_TO_REPLACE  and SLAVE_INDEX are meant to be replaced
# with template processing
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: CLUSER_NAME_TO_REPLACE-master
spec:
  serviceName: CLUSER_NAME_TO_REPLACE-write
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        role: master
        cluster: CLUSER_NAME_TO_REPLACE
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: postgres
        image: thirtyx/postgres:0.0.1-dev
        env:
          - name: POSTGRES_PASSWORD
            value: password
          - name: PGDATA
            value: /var/lib/postgresql/data
          - name: PGMOUNT
            value: /var/lib/postgresql            
          - name: MEMBER_ROLE
            value: master
          - name: SYNCHONROUS_REPLICAS
            value: "SLAVE_INDEX"
        ports:
          - containerPort: 5432
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /var/lib/postgresql
            name: pg-data
  volumeClaimTemplates:
  - metadata:
      name: pg-data
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
