# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: edgexpostgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: edgexpostgres
  # *.edgexpostgres.default.svc.cluster.local
  clusterIP: None
  selector:
    app: postgres
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: edgexpostgres
spec:
  serviceName: edgexpostgres
  replicas: 2
  template:
    metadata:
      labels:
        app: postgres
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: postgres
        image: thirtyx/postgres:0.0.1-dev
        env:
          - name: POSTGRES_PASSWORD
            value: password
          - name: PGDATA
            value: /var/lib/postgresql/data
        ports:
          - containerPort: 5432
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /var/lib/postgresql
            name: pg-data
          - mountPath: /var/lib/otherdata
            name: other-data
  volumeClaimTemplates:
  - metadata:
      name: pg-data
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
  - metadata:
      name: other-data
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
