apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: postgres-CLUSER_NAME_TO_REPLACE-DISK_INDEX
spec:
  # Always 1 replica, we have a different RC per PG instance
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        role: slave
        cluster: "CLUSER_NAME_TO_REPLACE"
        read: "true"
        index: "DISK_INDEX"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: postgres
        image: thirtyx/postgres:0.0.3-dev
        env:
          - name: POSTGRES_PASSWORD
            value: password
          - name: PGDATA
            value: /pgdata/data
          - name: PGMOUNT
            value: /pgdata
          - name: MEMBER_ROLE
            value: slave
          - name: MASTER_ENDPOINT
            value: postgres-CLUSER_NAME_TO_REPLACE-write
            #The name of the synchronous replica.  This will need to be included
            # in the string for the variable of the master node
          - name: SYNCHONROUS_REPLICA
            value: "SLAVE_INDEX"
        ports:
          - containerPort: 5432
        volumeMounts:
        - mountPath: /pgdata
          name:  pg-data-CLUSER_NAME_TO_REPLACE-DISK_INDEX
        imagePullPolicy: Always
      volumes:
      - name: pg-data-CLUSER_NAME_TO_REPLACE-DISK_INDEX
        persistentVolumeClaim:
          claimName: pg-data-CLUSER_NAME_TO_REPLACE-DISK_INDEX
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pg-data-CLUSER_NAME_TO_REPLACE-DISK_INDEX
  annotations:
    volume.beta.kubernetes.io/storage-class: postgresv1
  labels:
    app: postgres
    cluster: "CLUSER_NAME_TO_REPLACE"
    index: "DISK_INDEX"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

  # selector:
  #   matchLabels:
  #       app: postgres
  #       role: master
  #       cluster: CLUSER_NAME_TO_REPLACE
  #       mountid1234: mountid1234
