# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: devpostgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: devpostgres
  # *.devpostgres.toddnine.svc.cluster.local
  clusterIP: None
  selector:
    app: postgres
  type: LoadBalancer
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: devpostgres
spec:
  serviceName: devpostgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: postgres
        image:  postgres:9.5.4
        env:
          - name: POSTGRES_PASSWORD
            value: password
          - name: PGDATA
            value: /var/lib/postgresql/data
        ports:
          - containerPort: 5432
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /var/lib/postgresql
            name: pg-data
  volumeClaimTemplates:
  - metadata:
      name: pg-data
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
